name: update-commit-hashes

on:
  schedule:
    # Every day at 12:37am
    # Choose a random time near midnight because it may be delayed if there are high loads
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    - cron: 37 0 * * *
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  update-xla-commit-hash:
    uses: ./.github/workflows/_update-commit-hash.yml
    with:
      repo-name: xla
      branch: master
    secrets:
      MERGEBOT_TOKEN: ${{ secrets.PAT }}

  update-torchdynamo-commit-hash:
    uses: ./.github/workflows/_update-commit-hash.yml
    with:
      repo-name: torchdynamo
      branch: main
    secrets:
      MERGEBOT_TOKEN: ${{ secrets.PAT }}
