name: Update xla commit hash

on:
  workflow_dispatch:

env:
  NEW_BRANCH_NAME: clee2000/xla/${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
jobs:
  update-xla-commit-hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: false
          token: ${{ secrets.PAT }}
      - name: Checkout xla
        shell: bash
        run: |
          git clone https://github.com/pytorch/xla.git --depth=1 --quiet
      - name: Get new commit hash and update file
        id: update-file
        shell: bash
        run: |
          echo "::set-output name=original_commit::$(cat .github/xla_commit_hash.txt)"
          pushd xla
          git rev-parse master > ../.github/xla_commit_hash.txt
          popd
          if [[ $(git diff --exit-code .github/xla_commit_hash.txt) ]]; then
            git checkout -b "${NEW_BRANCH_NAME}"
            git config --global user.email "csl@fb.com"
            git config --global user.name "Catherine Lee"
            git add .github/xla_commit_hash.txt
            git commit -m "update xla commit hash"
            git push --set-upstream origin "${NEW_BRANCH_NAME}"
            echo "::set-output name=new_commit::$(cat .github/xla_commit_hash.txt)"
          fi
      - name: Create Pull Request
        uses: actions/github-script@v6
        if: ${{ steps.update-file.outputs.new_commit }}
        env:
          ORIGINAL_COMMIT: ${{ steps.update-file.outputs.original_commit }}
          NEW_COMMIT: ${{ steps.update-file.outputs.new_commit }}
          THING: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { repo, owner } = context.repo;
            const { NEW_BRANCH_NAME, NEW_COMMIT, ORIGINAL_COMMIT, GITHUB_TOKEN } = process.env
            github.token = GITHUB_TOKEN
            const result = await github.rest.pulls.create({
              title: '[XLA hash update] update the pinned xla hash',
              owner,
              repo,
              head: `${NEW_BRANCH_NAME}`,
              base: 'master',
              body: [
                'This PR is auto-generated nightly by [this action](https://github.com/clee2000/pytorch/blob/master/.github/workflows/xla-commit-hash.yml).\n',
                `Update the pinned xla hash from \`${ORIGINAL_COMMIT}\` to \`${NEW_COMMIT}\`.`
              ].join('')
            });
